[network]
env = "mainnet"
mode = "paper"
wallet_private_key = "0000000000000000000000000000000000000000000000000000000000000001"

[strategy]
type = "grid"
asset = "BTC"

[strategy.params]
grid_levels = 30
grid_mode = "arithmetic"
lower_price = 91900.0
upper_price = 92200.0
total_investment = 1000.0
# trigger_price = 29.34 # Commented out to start immediately
[log]
level = "info"
