[network]
env = "mainnet"
mode = "paper"
wallet_private_key = "0000000000000000000000000000000000000000000000000000000000000001"

[strategy]
type = "spot_grid"
asset = "HYPE/USDC"

[strategy.params]
grid_levels = 200
grid_mode = "arithmetic"
lower_price = 27
upper_price = 33
total_investment = 10000.0
[log]
level = "info"

[server]
enabled = true
port = 3000
host = "127.0.0.1"
